app.py
from flask import Flask
from blueprints.main import main

app = Flask(__name__)

# Register Blueprints
app.register_blueprint(main)

print("Debug mode is", app.debug)


if __name__ == '__main__':
    app.run(debug=True)

blueprints/main.py
from flask import Blueprint, render_template, request, send_file
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import io
import requests
import os
import zipfile


main = Blueprint('main', __name__)

# Konfigurasi
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name('credentials.json', scope)
client = gspread.authorize(creds)

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/application')
def application():
    return render_template('application.html')

@main.route('/dgs', methods=['GET', 'POST'])
def dgs():
    if request.method == 'POST':
        sheet_url = request.form['sheet_url']
        sheet_name = request.form['sheet_name']
        
        try:
            # Ambil spreadsheet dan worksheet
            spreadsheet = client.open_by_url(sheet_url)
            worksheet = spreadsheet.worksheet(sheet_name)
            
            # Ambil data dari worksheet
            data = worksheet.get_all_records()
            df = pd.DataFrame(data)
            
            # Konversi semua kolom menjadi string
            df = df.astype(str)
            
            # Simpan DataFrame sebagai XLSX
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name='Sheet1')
            output.seek(0)
            
            return send_file(output, as_attachment=True, download_name='download.xlsx')
        except Exception as e:
            return f"An error occurred: {e}"

    return render_template('dgs.html')

@main.route('/upload_and_send', methods=['GET', 'POST'])
def upload_and_send():
    if request.method == 'POST':
        sheet_url = request.form['sheet_url']
        sheet_name = request.form['sheet_name']
        file = request.files['file']

        try:
            # Baca file XLSX
            df = pd.read_excel(file)
            
            # Konversi semua kolom menjadi string
            df = df.astype(str)
            
            # Debug: Tampilkan data yang akan dikirim
           

            # Ambil spreadsheet dan worksheet
            spreadsheet = client.open_by_url(sheet_url)
            worksheet = spreadsheet.worksheet(sheet_name)
            
            # Kosongkan worksheet sebelum mengisi data baru
            worksheet.clear()
            
            # Konversi DataFrame ke format list of lists
            data = df.values.tolist()

            # Debug: Tampilkan data yang akan diupdate ke Google Sheets
            print("Data to be uploaded to Google Sheets:")
            print(data)

            # Update worksheet dengan data baru
            worksheet.update('A1', [df.columns.tolist()] + data)

            return "Data successfully uploaded to Google Sheets!"

        except Exception as e:
            return f"An error occurred: {e}"

    # Untuk metode GET, render form
    return render_template('upload_and_send.html')

@main.route('/convert_csv_to_xlsx', methods=['GET', 'POST'])
def convert_csv_to_xlsx():
    if request.method == 'POST':
        # Ambil file dan delimiter dari form
        file = request.files['file']
        delimiter = request.form['delimiter']

        try:
            # Baca CSV menggunakan delimiter yang diinputkan
            df = pd.read_csv(file, delimiter=delimiter)
            df = df.astype(str)
            # Simpan DataFrame sebagai file XLSX
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name='Sheet1')
            output.seek(0)

            # Kirim file XLSX sebagai lampiran
            return send_file(output, as_attachment=True, download_name='converted.xlsx')
        except Exception as e:
            return f"An error occurred: {e}"

    return render_template('convert_csv_to_xlsx.html')


@main.route('/combine_xlsx', methods=['GET', 'POST'])
def combine_xlsx():
    if request.method == 'POST':
        files = request.files.getlist('files')

        try:
            # List untuk menyimpan DataFrame dari setiap file
            dfs = []

            for file in files:
                df = pd.read_excel(file)
                df = df.astype(str)
                dfs.append(df)

            # Gabungkan semua DataFrame menjadi satu
            combined_df = pd.concat(dfs, ignore_index=True)

            # Simpan DataFrame gabungan sebagai file XLSX
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                combined_df.to_excel(writer, index=False, sheet_name='Combined')
            output.seek(0)

            # Kirim file XLSX gabungan sebagai lampiran
            return send_file(output, as_attachment=True, download_name='combined.xlsx')
        except Exception as e:
            return f"An error occurred: {e}"

    return render_template('combine_xlsx.html')


@main.route('/download_files', methods=['GET', 'POST'])
def download_files():
    if request.method == 'POST':
        sheet_url = request.form['sheet_url']
        sheet_name = request.form['sheet_name']
        formats = request.form['formats'].split(',')  # Ambil format file dari form

        try:
            # Buka spreadsheet dan worksheet
            spreadsheet = client.open_by_url(sheet_url)
            worksheet = spreadsheet.worksheet(sheet_name)

            # Ambil data dari sheet
            rows = worksheet.get_all_values()
            headers = rows[0]
            data = rows[1:]

            # Inisialisasi file ZIP
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
                for index, row in enumerate(data):
                    if len(row) < 2:
                        continue  # Skip rows without enough data
                    
                    unique_name = row[0]  # Nama unik dari kolom pertama
                    links = row[1:3]  # Link dari kolom kedua dan ketiga

                    # Jika ada lebih banyak format daripada link, kita gunakan format default untuk sisa link
                    if len(formats) < len(links):
                        formats.extend(['.unknown'] * (len(links) - len(formats)))

                    for i, (link, file_format) in enumerate(zip(links, formats)):
                        if link and link.startswith("https://drive.google.com"):
                            try:
                                # Extract file ID from the link
                                file_id = link.split('/')[-2]
                                # Generate the download URL
                                download_url = f"https://drive.google.com/uc?id={file_id}&export=download"
                                
                                # Mendapatkan nama file dari header link dan format
                                header = headers[i + 1] if i + 1 < len(headers) else "unknown"
                                file_name = f"{index + 1}_{unique_name}_{header}{file_format}"  # Format file ditambahkan di sini

                                # Unduh file
                                response = requests.get(download_url, stream=True)
                                if response.status_code == 200:
                                    zip_file.writestr(file_name, response.content)
                                else:
                                    print(f"Failed to download file from {link}")

                            except Exception as e:
                                print(f"Error downloading file from link: {link}\n{e}")

            zip_buffer.seek(0)
            return send_file(zip_buffer, as_attachment=True, download_name='files.zip')

        except Exception as e:
            return f"An error occurred: {e}"

    return render_template('download_files.html')

templates/about.html
{% extends "layout.html" %}

{% block title %}About - Gus Poer{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>About</h1>

    <div class="container main-content">
        <div class="row">
            <div class="col-md-12">
                <h2>Tentang Agus Purwanto</h2>
                <p>Halo, saya Agus Purwanto, seorang pengembang Python dengan pengalaman lebih dari 5 tahun
                    dalam merancang dan mengembangkan solusi perangkat lunak yang inovatif dan efisien. Keahlian saya
                    mencakup berbagai aspek pemrograman Python, mulai dari pengembangan aplikasi web hingga analisis
                    data dan otomatisasi.</p>

                <h3>Keahlian Utama:</h3>
                <ul>
                    <li><strong>Pengembangan Aplikasi Web:</strong> Berpengalaman dalam menggunakan framework seperti
                        Django dan Flask untuk membangun aplikasi web yang kuat dan responsif.</li>
                    <li><strong>Analisis Data:</strong> Menguasai alat dan pustaka seperti Pandas, NumPy, dan Matplotlib
                        untuk memproses dan menganalisis data besar.</li>
                    <li><strong>Automatisasi dan Scripting:</strong> Mampu membuat skrip Python untuk otomatisasi proses
                        bisnis dan integrasi sistem.</li>
                    <li><strong>Pengembangan API:</strong> Keterampilan dalam merancang dan mengembangkan API RESTful
                        untuk berbagai kebutuhan aplikasi.</li>
                </ul>


                <h3>Pendekatan Kami:</h3>
                <p>Saya berfokus pada solusi yang memenuhi kebutuhan spesifik klien dengan pendekatan yang detail dan
                    terstruktur. Saya percaya pada pentingnya komunikasi yang efektif dan pemahaman yang mendalam
                    tentang masalah yang dihadapi untuk memberikan hasil terbaik.</p>

                <h3>Mengapa Memilih Saya:</h3>
                <ul>
                    <li><strong>Keahlian Teknis:</strong> Pengalaman luas dalam berbagai teknologi dan pustaka Python.
                    </li>
                    <li><strong>Pendekatan Kolaboratif:</strong> Bekerja sama dengan klien untuk memastikan solusi yang
                        dirancang sesuai dengan harapan dan kebutuhan mereka.</li>
                    <li><strong>Komitmen terhadap Kualitas:</strong> Selalu berusaha memberikan hasil yang berkualitas
                        tinggi dan mematuhi tenggat waktu.</li>
                </ul>

                <p>Jika Anda tertarik untuk bekerja sama atau memiliki pertanyaan lebih lanjut tentang proyek atau
                    layanan saya, jangan ragu untuk menghubungi saya melalui <a
                        href="mailto:agus.p.wan.2@gmail.com">email</a> atau <a href="https://wa.me/6282244197463">kontak
                        WA</a>.</p>

                <p>Terima kasih telah mengunjungi portofolio saya. Saya menantikan kesempatan untuk bekerja sama dan
                    membantu Anda mencapai tujuan teknis Anda.</p>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/application.html
{% extends "layout.html" %}

{% block title %}Application - Gus Poer{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Application List</h1>
    <ul class="list-group">
        <li class="list-group-item">
            <a class="link-primary" href="{{ url_for('main.dgs') }}">Download Google Sheet as XLSX</a>
        </li>
        <li class="list-group-item">
            <a class="link-primary" href="{{ url_for('main.upload_and_send') }}">Upload XLSX and Send to Google Sheets</a>
        </li>
        <li class="list-group-item">
            <a class="link-primary" href="{{ url_for('main.convert_csv_to_xlsx') }}">Convert csv to xlsx</a>
        </li>
        <li class="list-group-item">
            <a class="link-primary" href="{{ url_for('main.combine_xlsx') }}">Combine xlsx</a>
        </li>
    </li>
    <li class="list-group-item">
        <a class="link-primary" href="{{ url_for('main.download_files') }}">Download Files from Google Drive</a>
    </li>
    </ul>
</div>
{% endblock %}

templates/combine_xlsx.html
{% extends "layout.html" %}

{% block title %}Combine Multiple XLSX Files{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Combine Multiple XLSX Files</h1>
    <form method="post" enctype="multipart/form-data" action="{{ url_for('main.combine_xlsx') }}">
        <div class="form-group">
            <label for="files">Upload XLSX Files:</label>
            <input type="file" id="files" name="files" class="form-control" accept=".xlsx" multiple required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Combine Files</button>
    </form>
</div>
{% endblock %}

templates/convert_csv_to_xlsx.html
{% extends "layout.html" %}

{% block title %}Convert CSV to XLSX{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Convert CSV to XLSX</h1>
    <form method="post" enctype="multipart/form-data" action="{{ url_for('main.convert_csv_to_xlsx') }}">
        <div class="form-group">
            <label for="file">Upload CSV File:</label>
            <input type="file" id="file" name="file" class="form-control" accept=".csv" required>
        </div>
        <div class="form-group">
            <label for="delimiter">Delimiter:</label>
            <input type="text" id="delimiter" name="delimiter" class="form-control" placeholder="e.g., , or ; or #" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Convert to XLSX</button>
    </form>
</div>
{% endblock %}

templates/dgs.html
{% extends "layout.html" %}

{% block title %}Download Google Sheet as XLSX - Gus Poer{% endblock %}

{% block content %}

<div class="container mt-5">
    <h1 class="mb-4">Download Google Sheet as XLSX</h1>
    <form method="post">
        <div class="mb-3">
            <label for="sheet_url" class="form-label">Google Sheet URL:</label>
            <input type="text" class="form-control" id="sheet_url" name="sheet_url" required>
        </div>
        <div class="mb-3">
            <label for="sheet_name" class="form-label">Sheet Name:</label>
            <input type="text" class="form-control" id="sheet_name" name="sheet_name" required>
        </div>
        <button type="submit" class="btn btn-primary">Download XLSX</button>
    </form>
</div>

{% endblock %}

templates/download_files.html
{% extends "layout.html" %}

{% block title %}Download Files from Google Drive{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Download Files</h1>
    <form method="post" action="{{ url_for('main.download_files') }}">
        <div class="form-group">
            <label for="sheet_url">Google Sheets URL</label>
            <input type="url" class="form-control" id="sheet_url" name="sheet_url" required>
        </div>
        <div class="form-group">
            <label for="sheet_name">Sheet Name</label>
            <input type="text" class="form-control" id="sheet_name" name="sheet_name" required>
        </div>
        <div class="form-group">
            <label for="formats">File Formats (comma separated, e.g., .pdf,.jpg)</label>
            <input type="text" class="form-control" id="formats" name="formats" required>
        </div>
        <button type="submit" class="btn btn-primary">Download Files</button>
    </form>
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}Home - Gus Poer{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Selamat Datang di Portofolio Agus Purwanto</h1>
    <p class="lead">Saya Agus Purwanto, Di sini, Anda dapat melihat proyek-proyek yang telah saya kerjakan dan bagaimana saya dapat membantu Anda mencapai tujuan Anda. Hubungi saya untuk diskusi lebih lanjut!</p>
    <hr class="my-4">
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Gus Poer{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Gus-Poer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if request.endpoint == 'main.home' else '' }}"
                            href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if request.endpoint == 'main.application' else '' }}"
                            href="{{ url_for('main.application') }}">Application</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if request.endpoint == 'main.about' else '' }}"
                            href="{{ url_for('main.about') }}">About</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/upload_and_send.html
{% extends "layout.html" %}

{% block title %}Upload XLSX and Send to Google Sheets - Gus Poer{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Upload XLSX and Send to Google Sheets</h1>
    <form method="post" enctype="multipart/form-data" action="{{ url_for('main.upload_and_send') }}">
        <div class="mb-3">
            <label for="sheet_url" class="form-label">Google Sheet URL:</label>
            <input type="text" id="sheet_url" name="sheet_url" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="sheet_name" class="form-label">Target Sheet Name:</label>
            <input type="text" id="sheet_name" name="sheet_name" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="file" class="form-label">Upload XLSX File:</label>
            <input type="file" id="file" name="file" class="form-control" accept=".xlsx" required>
        </div>
        <button type="submit" class="btn btn-primary">Upload and Send</button>
    </form>
</div>
{% endblock %}